crawling/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name ='live'
urlpatterns = [  
    path('platform/<int:platform>',views.platform,name='get_platform'),
    path('getAll/<int:platform>',views.ret_stream,name='get_all'),
    path('getslide/',views.getslide,name='get_slide'),
    path('get_main_thumb/<int:platform>',views.get_main_thumbnail , name='get_main_thumbnail'),
]

hotplay/subfunction/urls.py
from django.urls import path
from . import views as boot_views
from crawling import views as craw_views
from accounts import views as account_views
from crawling.views import frequnctly
urlpatterns = [
    path('', boot_views.index, name="boot"),
    path('double_screen/', boot_views.double_screen, name="double_screen"),
    path('show_stream/<int:stream_id>',boot_views.show_one_stream, name="show_one"),

    path('login/', account_views.login, name="login"),
    path('logout/', account_views.logout, name="logout"),
    path('signup/', account_views.signup, name="signup"),
    path('favorite/',account_views.favorite, name="favorite"),
    path('favlist/',account_views.favlist, name="favlist"),

    path('crawling_stream_all/',craw_views.fre_test, name="crawling_stream"),
]   
frequnctly()

hotplay/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('subfunction.urls')),
    path('live/', include('crawling.urls')),
    path('accounts/',include('accounts.urls'))
]

subfunction/urls.py
from django.urls import path
from . import views as boot_views
from crawling import views as craw_views
from accounts import views as account_views
from crawling.views import frequnctly
urlpatterns = [
    path('', boot_views.index, name="boot"),
    path('double_screen/', boot_views.double_screen, name="double_screen"),
    path('show_stream/<int:stream_id>',boot_views.show_one_stream, name="show_one"),

    path('login/', account_views.login, name="login"),
    path('logout/', account_views.logout, name="logout"),
    path('signup/', account_views.signup, name="signup"),
    path('favorite/',account_views.favorite, name="favorite"),
    path('favlist/',account_views.favlist, name="favlist"),

    path('crawling_stream_all/',craw_views.frequnctly, name="crawling_stream"),
]   
# frequnctly()

subfunction/models.py
from django.db import models

subfunction/views.py
from django.shortcuts import render, redirect
from django.http.response import HttpResponse
import json
from django.shortcuts import render
from crawling.models import Stream
from django.db.models import Q

# Create your views here.
def index(request):    
    return render(request, 'index.html',) 

def twitch(request):
    return render(request, 'twitch.html')
def getlives(request):
    return render(request , 'slide.html')

def double_screen(request):
    return render(request, 'double_screen.html')

def search(request):
    keyword = request.GET["keyword"]
    result = Stream.objects.filter(Q(channel_name__contains=keyword)| Q(title__contains=keyword))
    context = {
        'results':result
    }
    return render(request,'subfunction/search_result.html',context)

def show_one_stream(request,stream_id):
    stream = Stream.objects.get(id=stream_id)
    a = ''
    if stream.platform == 0:
        l = stream.stream_url.split('/')
        a = f'https://www.twitch.tv/embed/{l[-1]}/chat'        
    context = {
        'stream':stream,
        'chat':a

    }
    return render(request,'subfunction/one_stream.html',context)

subfunction/templates/double_screen.html
{% extends 'base.html' %}
{% block stylesheet %}
<link rel="canonical" href="https://getbootstrap.com/docs/4.4/examples/album/">

<!-- Bootstrap core CSS -->
<link href="https://getbootstrap.com/docs/4.4/dist/css/bootstrap.min.css" rel="stylesheet">

<!-- Favicons -->
<link rel="apple-touch-icon" href="https://getbootstrap.com/docs/4.4/assets/img/favicons/apple-touch-icon.png"
    sizes="180x180">
<link rel="icon" href="https://getbootstrap.com/docs/4.4/assets/img/favicons/favicon-32x32.png" sizes="32x32"
    type="image/png">
<link rel="icon" href="https://getbootstrap.com/docs/4.4/assets/img/favicons/favicon-16x16.png" sizes="16x16"
    type="image/png">
<link rel="manifest" href="https://getbootstrap.com/docs/4.4/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="https://getbootstrap.com/docs/4.4/assets/img/favicons/safari-pinned-tab.svg"
    color="#563d7c">
<link rel="icon" href="https://getbootstrap.com/docs/4.4/assets/img/favicons/favicon.ico">
<meta name="msapplication-config" content="https://getbootstrap.com/docs/4.4/assets/img/favicons/browserconfig.xml">
<meta name="theme-color" content="#563d7c">
<link href="https://getbootstrap.com/docs/4.4/examples/album/album.css" rel="stylesheet">

<style>
    .w-30 {
        margin: auto;
        float: left;
        width: 20rem;
    }

    .btn-close {
        display: none;
    }

    .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
    }

    @media (min-width: 768px) {
        .bd-placeholder-img-lg {
            font-size: 3.5rem;
        }
    }
</style>
{% endblock %}

{% block content %}
<div class="multiscreen row row-cols-2 mb-5 mt-5" style="width:-webkit-fill-available; border: solid; background-color:#808080">
    <span class="col target-screen-left mt-3 mb-3">
        <div style="position:relative">            
            <iframe id="screen-left" class="d-block w-100" width="100%" height="100%" src="" frameborder="0"
                allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                allowfullscreen></iframe>
            <button style="position:absolute; right:0; top:0px; background:#ffc107;width:25px;height:25px;"
                class="btn btn-warning btn-close" id="btn-close-left" data-target="left"><i class="fas fa-times"></i></button>
        </div>
    </span>
    <span class="col target-screen-right mt-3 mb-3" style="border-left:solid;">
        <div style="position:relative">
            <iframe id="screen-right" class="d-block w-100" width="500" height="300" src="" frameborder="0"
                allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                allowfullscreen></iframe>
            <button style="position:absolute; right:0; top:0px; background:#ffc107;width:15px;height:15px;"
                class="btn btn-warning btn-close text-center" id="btn-close-right" data-target="right"><i class="mt-0 fas fa-times"></i></button>
        </div>
    </span>
</div>

<!-- ------------ LIST ------------- -->
<div class="row">
    <span class="hotel-rooms  w-30 lists">

    </span>
</div>

<script src="https://code.jquery.com/jquery-3.4.1.min.js"
    integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
</script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
</script>
<script src="https://kit.fontawesome.com/41ac120a10.js" crossorigin="anonymous"></script>
<script>
    $(function () {
        $(document).on('click', '.site-btn', function () {
            var target = $(this).data('target')
            $('#screen-' + target).attr('src', $(this).val())
            $('#btn-close-' + target).show()
        });
        $(document).on('click', '.btn-close', function () {
            var target = $(this).data('target')
            $('#screen-' + target).attr('src', '')
            $('#btn-close-' + target).hide()
        });
    })
    $(function () {
        $.ajax({
            url: '{% url "live:get_all" 3 %}',
            method: 'POST',
            data: {
                csrfmiddlewaretoken: '{{csrf_token}}'
            },
            success: function (data) {
                $('.lists').append(data);
                // 데이터를 불러와서 어느쪽 리스트 인지 고르기
            },
            error: function (data) {
                alert("twitch fail");
            }
        })
    });
</script>
{% endblock %}

subfunction/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block stylesheet %}
.container {
}
.w-30 {
    margin: auto;
    float: left;
    width: 20rem;
}
.slide-thumbnail{
    width:500px;
    heught:300px;
}
.carousel-btn{
  width:7rem;
  margin-bottom:4rem;
  margin-top:4rem
}
{% endblock stylesheet %}
<!-- Begin Page Content -->
{% block slide %}
<div style="width:100%; background-color : ivory;">
<div id="outsidebg" class=" bg-white">
  <!-- Page Heading -->
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <div id="carouselExampleControls" class="container carousel slide"  data-ride="carousel"
      data-interval="false">
      <div class="carousel-inner">
        
      </div>
      <a class="carousel-control-prev carousel-btn" href="#carouselExampleControls" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next carousel-btn" href="#carouselExampleControls" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>
</div>
{% endblock slide %}
{% block content %}
  <!-- Content Row (PlatForm Video Position) -->
  <div class="row">

    <div class="home_categories_ctn" id="contentbg">
      <!-- 전체 배경 화면 색이 위 class에 잡혀있는데 우리가 가지고 있는 파일에서 수정
              불가, 그래서 style을 줘서 변경해야 할 듯 -->
      <div class="home_pagecontent_ctn" id="sale_tag_categories">


        <!-- First PlatForm Start -->
        <div class="home_category_ctn">
          <div class="home_category_title_ctn" style="background: #6441a5">
            <!-- style="background: linear-gradient( 330deg, #96436a 0%, #e0744a 90% );" 나중에 그라데이션 추가-->
            <div class="home_category_title">
              <span style="font-weight: bold; font-size: 1.25em; line-height:100px;">Twitch<br></span>
              <span style="font-weight: bold; font-size: 1.25em; line-height:100px;">TV<br></span>
            </div>
          </div>
          <div class="home_category_games_ctn" id="twitch_main" style="background: rgba( 150, 67, 106, 0.3 );">
          </div>
          <a class="see_more_link" href="{% url 'live:get_platform' 0 %}">See more...
          </a>
        </div>
        <!-- First PlatForm End -->




        <!-- Second  PlatForm Start -->
        <div class="home_category_ctn">
          <div class="home_category_title_ctn" style="background:#FF0000">
            <!-- linear-gradient( 330deg, #c98446 0%, #d9ab64 45%, #eed290 90% ); -->
            <div class="home_category_title">
              <span style="font-weight: bold; font-size: 1.25em; line-height:100px;">YOUTUBE<br></span>
              <span style="font-weight: bold; font-size: 1.25em; line-height:100px;">LIVE<br></span>
            </div>
          </div>
          <div class="home_category_games_ctn" id="youtube_main" style="background: rgba( 201, 132, 70, 0.3 );">
          </div>
          <a class="see_more_link" href="{% url 'live:get_platform' 1 %}">See more...
          </a>
        </div>
        <!-- Second PlatForm End -->




        <!-- Third PlatForm Start -->
        <div class="home_category_ctn">
          <div class="home_category_title_ctn" style="background: #1b4de8">
            <!--linear-gradient( 330deg, #c98446 0%, #d9ab64 45%, #eed290 90% );  -->
            <!-- 1b4de8 -->
            <div class="home_category_title">
              <span style="font-weight: bold; font-size: 1.25em; line-height:100px;">Afreeca<br></span>
              <span style="font-weight: bold; font-size: 1.25em; line-height:100px;">TV<br></span>
            </div>
          </div>
          <div class="home_category_games_ctn" id="afreeca_main" style="background: rgba( 201, 132, 70, 0.3 );">
          </div>
          <a class="see_more_link" href="{% url 'live:get_platform' 2 %}">See more...
          </a>
        </div>
        <!-- Third PlatForm End -->


      </div>
    </div>
  </div>



  <!-- END PlatForm Video Position -->


  <!-- /.container-fluid -->

</div>
<!-- End of Main Content -->
{% endblock %}

{% block script %}
<script>
  function get_thumb(platform) {
    var url = '{% url "live:get_main_thumbnail" 1234 %}'.replace('1234', platform)
    var target = ''
    if (platform == 0)
      target = '#twitch_main'
    else if (platform == 1)
      target = '#youtube_main'
    else
      target = '#afreeca_main'
    $.ajax({
      url: url,
      method: 'POST',
      data: {
        csrfmiddlewaretoken: '{{csrf_token}}'
      },
      success: function (data) {
        $(target).append(data);
      },
      error: function (data) {
        console.log("getThumbnails fail");
      }
    })
  }
  $(function () {    
    var be4 = 0
    var be4url =''
    $('#carouselExampleControls').on('slide.bs.carousel',
      function () { //슬라이드가 이동 시작 , 이전 녀석의 영상을 썸네일로 바꾸고 이동한다.
        var cur = $('div.active').find('input')[0]['value'];
        be4=cur        
        var url = $('#stream-url-' + cur).val()
        be4url = url
        var total = $('.carousel-item').length;
        {% comment %} $('#stream-' + cur).attr('src', '') {% endcomment %}
      })
    $('#carouselExampleControls').on('slid.bs.carousel',
      function () { //슬라이드가 이동 완료 시 썸네일을 영상으로 바꾼다
        var cur = $('div.active').find('input')[0]['value']; // 현재 슬라이드
        console.log(cur)
        var total = $('.carousel-item').length; // 전체 슬라이드
        var url = $('#stream-url-' + cur).val();
        {% comment %} $('#thumbnail-'+cur).hide()
        $('#thumbnail-'+be4).show() {% endcomment %}
        {% comment %} $('#stream-' + cur).show() {% endcomment %}
        {% comment %} $('#stream-' + be4).hide() {% endcomment %}
        $('#stream-' + be4).attr('src', '')
        {% comment %} $('#stream-' + be4).attr('src', be4url) {% endcomment %}
        $('#stream-' + cur).attr('src', url)
      })
    $.ajax({
      url: '{% url "live:get_slide" %}',
      method: 'POST',
      data: {
        csrfmiddlewaretoken: '{{csrf_token}}'
      },
      success: function (data) {
        $('.carousel-inner').append(data);
        var first = $(document).find('.carousel-inner div:first')
        first.addClass('active')
        var cur = first.find('input')[0]['value'];
        var url = $('#stream-url-' + cur).val();
        $('#stream-' + cur).attr('src', url)
        
      },
      error: function (data) {
        console.log("getSlide fail");
      }
    })
    get_thumb(0)
    get_thumb(1)
    get_thumb(2)
    $(document).on('click','.btn-fav',function(){
        var id = $(this).data('id')
        var button = $(this)
        console.log(button)
        $.ajax({
          url:'{% url "favorite" %}',
          method:'POST',
          data:{
            csrfmiddlewaretoken:'{{csrf_token }}',
            stream:id
          },
          success:function(data){
            button.find('i').toggleClass(['fas','far'])
            button.toggleClass('text-white')
          },
          error:function(data){

          }
        })
    })    
  });
  function offline(id){
    $('#thumbnail-'+id).attr('src','{% static "img/offline2.jpg" %}');
  }
  
</script>
{% endblock script %}

subfunction/templates/slide.html
{% extends 'index.html' %}
{% block stylesheet %}
.container {
}
.w-30 {
    margin: auto;
    float: left;
    width: 20rem;
}
.slide-thumbnail{
    width:500px;
    heught:300px;
}
{% endblock %}
{% block randomBox %}
    <div id="carouselExampleControls" class="container carousel slide"  data-ride="carousel"
        data-interval="false">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <input type="hidden" class="idstore" value="1">
                <input type="hidden" id="stream-url-1" value="https://player.twitch.tv/?channel=handongsuk">
                <img id="thumbnail-1" src="https://static-cdn.jtvnw.net/previews-ttv/live_user_handongsuk-320x180.jpg">
                <iframe id="stream-1" class="d-block w-100" width="500" height="300" src=""
                    frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                    allowfullscreen></iframe>
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    {% endblock %}
    {% block streamList %}
    <div class="container">
        <span class="w-30">
            <table class="table table-striped table-bordered table-hover youtube">
                <thead class="thead-light">
                    <th scope="col">Youtube</th>
                </thead>
                <td id="youtube-be4">
                    <img src="https://media.giphy.com/media/jAYUbVXgESSti/giphy.gif">
                </td>
            </table>
        </span>
        <span class="w-30">
            <table class="table table-striped table-bordered table-hover twitch">
                <thead class="thead-light">
                    <th scope="col">Twitch</th>
                </thead>
                <td id="twitch-be4">
                    <img src="https://media.giphy.com/media/jAYUbVXgESSti/giphy.gif">
                </td>
            </table>

        </span>
        <span class="w-30">
            <table class="table table-striped table-bordered table-hover afreeca">
                <thead class="thead-light">
                    <th scope="col">Afreeca</th>
                </thead>
                <td id="afreeca-be4">
                    <img src="https://media.giphy.com/media/jAYUbVXgESSti/giphy.gif">
                </td>
            </table>
        </span>
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
    <script src="https://kit.fontawesome.com/41ac120a10.js" crossorigin="anonymous"></script>
    <script>
        $(function () {
            $('#carouselExampleControls').on('slide.bs.carousel',
                function () { //슬라이드가 이동 시작 , 이전 녀석의 영상을 썸네일로 바꾸고 이동한다.
                    var cur = $('div.active').find('input')[0]['value'];
                    var total = $('.carousel-item').length;
                    $('#stream-'+cur).hide()
                    $('#thumbnail-'+cur).show()
                    $('#stream-'+cur).attr('src','')
                })
            $('#carouselExampleControls').on('slid.bs.carousel',
                function () { //슬라이드가 이동 완료 시 썸네일을 영상으로 바꾼다
                    var cur = $('div.active').find('input')[0]['value']; // 현재 슬라이드
                    console.log(cur)
                    var total = $('.carousel-item').length; // 전체 슬라이드
                    var url = $('#stream-url-'+cur).val();
                    $('#thumbnail-'+cur).hide()
                    $('#stream-'+cur).attr('src',url)
                    $('#stream-'+cur).show() 
                })
            var id = $(this).data('id');
            console.log(id);
            
            $.ajax({
                url: '{% url "live:get_slide" %}',
                method: 'POST',
                data: {
                    csrfmiddlewaretoken: '{{csrf_token}}' 
                },
                success: function (data) {
                    $('.carousel-inner').append(data);
                },
                error: function (data) {
                    console.log("getSlide fail");
                }
            })
            $.ajax({
                url: '{% url "live:get_all" 0 %}',
                method: 'POST',
                data: {
                    csrfmiddlewaretoken: '{{csrf_token}}'
                },
                success: function (data) {
                    $('#twitch-be4').hide()
                    $('.twitch').append(data);
                },
                error: function (data) {
                    console.log("twitch fail");
                }
            })
            $.ajax({
                url: '{% url "live:get_all" 1 %}',
                method: 'POST',
                data: {
                    csrfmiddlewaretoken: '{{csrf_token}}'
                },
                success: function (data) {
                    $('#youtube-be4').hide()
                    $('.youtube').append(data);
                },
                error: function (data) {
                    console.log("youtube fail");
                }
            })
            $.ajax({
                url: '{% url "live:get_all" 2 %}',
                method: 'POST',
                data: {
                    csrfmiddlewaretoken: '{{csrf_token}}' // post로 보내주기 때문에 필요해
                },
                success: function (data) {
                    $('#afreeca-be4').hide()
                    $('.afreeca').append(data);
                },
                error: function (data) {
                    console.log("afreeca fail");                
                }
            })
        });
    </script>
{% endblock %}