accounts/urls.py
from django.urls import path , include
from . import views
from .views import check_validated_email
app_name='accounts'
urlpatterns = [
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('signup/', views.signup, name="signup"),
    path('activate/<str:uid64>/<str:token>',views.activate,name="activate"),
    
]
check_validated_email()

hotplay/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('subfunction.urls')),
    path('live/', include('crawling.urls')),
    path('accounts/',include('accounts.urls'))
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser,User
from crawling.models import Stream
import random
# Create your models here.
class User(AbstractUser):
    nickname = models.CharField(max_length=200)
    favorite = models.ManyToManyField(Stream, related_name="fav_user") 
    
    

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm , AuthenticationForm
from .models import User
from django.conf import settings
class CustomUserCreateionForm(UserCreationForm):
    nickname = forms.CharField(max_length=200)
    username = forms.CharField(min_length=4)
    email = forms.EmailField()
    class Meta(UserCreationForm.Meta):
        
        model = User
        fields = ['username', 'email']
        # 기존에 있던 field 에 하나더 추가 한다는 말.

class CustomAuthenticationForm(AuthenticationForm):
    class Meta(AuthenticationForm):
        model = User
        

accounts/views.py
from django.shortcuts import render , redirect
from .forms import AuthenticationForm,UserCreationForm 
from django.contrib.auth import login as  auth_login, logout as auth_logout
from .forms import CustomAuthenticationForm, CustomUserCreateionForm
from django.contrib.auth.models import User

from .models import User as User2

from crawling.models import Stream
from django.http.response import HttpResponse
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode,urlsafe_base64_decode
from django.core.mail import EmailMessage
from django.utils.encoding import force_bytes, force_text
from .tokens import account_activation_token
import json
import threading
import datetime
# Create your views here.
def check_validated_email():
    t1 = threading.Thread(target=delete_none_validated_email)
    t1.start()
    threading.Timer(86400,check_validated_email).start()
    return
def delete_none_validated_email():
    print("delete_none_validated_email start............")
    today = datetime.date.today()
    user = User2.objects.filter(is_active=False)
    cnt = 0
    for tmp in user:
        target_day = tmp.date_joined.date()
        if today - target_day>= datetime.timedelta(1):
            tmp.delete()
            cnt = cnt + 1
    print("delete done............")
    return
def signup(request):
    if not request.user.is_authenticated:
        if request.method == "POST":
            form = CustomUserCreateionForm(request.POST)  
            email = form['email']     

            if form.is_valid() :
                user = form.save()
                user.is_active = False
                user.save()

                
                # auth_login(request , form)
                current_site = get_current_site(request) 
                # localhost:8000
               
                message = render_to_string('accounts/activation_email.html',                         {

                    'user': user,
                    'domain': current_site.domain,
                    'uid': force_text(urlsafe_base64_encode(force_bytes(user.id))),
                    'token': account_activation_token.make_token(user),
                })
                mail_title = "계정 활성화 확인 이메일"
                mail_to = request.POST["email"]
                email = EmailMessage(mail_title,message, to=[mail_to])
                email.send()
                return HttpResponse(
                        '<div style="font-size: 40px; width: 100%; height:100%; display:flex; text-align:center; '
                        'justify-content: center; align-items: center;">'
                        '입력하신 이메일<span>로 인증 링크가 전송되었습니다.</span>'
                        '</div>')
        else:
            form = CustomUserCreateionForm()
        context={
            'form':form
        }
        return render(request , 'accounts/signup2.html', context)
    else:
        return redirect('boot')
def login(request):
    if request.user.is_authenticated:
        return redirect('boot')
    else:
        if request.method == "POST":
            form = CustomAuthenticationForm(request, request.POST)
            #문지기 form 이기 때문에 request와 reqeust.POST 두개의 인자를 받는다.
            if form.is_valid():
                user = form.get_user()
                auth_login(request, user)
                return redirect(request.GET.get('next')or 'boot')                
        else:
            form = CustomAuthenticationForm()
        context={
            'form':form
        }
        return render(request , 'accounts/login2.html', context)
def logout(request):
    auth_logout(request)
    return redirect('boot')

def favorite(request):
    if request.user.is_authenticated and request.method =="POST":
        id = request.POST['stream']
        user = request.user
        stream = Stream.objects.get(id=id)
        if request.user in stream.fav_user.all():           
            user.favorite.remove(stream)
        else:
            user.favorite.add(stream)
        context={
        }
        return HttpResponse(json.dumps(context),status=200,content_type='application/json')
    else:
        return redirect('boot')
def favlist(request):
    l = request.user.favorite.all()
    length= len(l)
    context = {
        'favs':l,
        'len':length

    }
    return render(request,'subfunction/favorite_list.html',context)

def activate(request, uid64, token):

    uid = force_text(urlsafe_base64_decode(uid64))
    user = User2.objects.get(id=uid)
    
    
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        #auth.login(request, user)
        return HttpResponse(
                        '<div style="font-size: 40px; width: 100%; height:100%; display:flex; text-align:center; '
                        'justify-content: center; align-items: center;">'
                        '인증완료</span>'
                        '</div>')
    else:
        return HttpResponse('비정상적인 접근입니다.')

accounts/templates/accounts/activation_email.html
{% autoescape off %}
    안녕하세요

    아래 링크를 클릭하면 회원가입 인증이 완료됩니다.
    
    {% comment %} 회원가입 링크 : http://{{ domain }}{% url 'accounts:activate' uid64=uid token=token %} {% endcomment %}

{% endautoescape %}

accounts/templates/accounts/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<h1>New article!@</h1>
<form action="" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}    
    <input type="submit" value="submit">
</form>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
<h1>login</h1>
{% block content %}
<form method="post">
    {% csrf_token %}
     {% bootstrap_form form %} 
    <button class="btn btn-primary">LOGIN</button>
</form>
{% endblock  %}

accounts/templates/accounts/login2.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>HOT Play</title>
  <!--Steam StyleSheet  -->
  <link href="https://use.typekit.net/bmd7vlq.css" rel="stylesheet" type="text/css">
  <link href="https://steamstore-a.akamaihd.net/public/shared/css/motiva_sans.css?v=FAK4O46_mOLB&amp;l=english"
    rel="stylesheet" type="text/css">
  <link href="https://steamstore-a.akamaihd.net/public/shared/css/shared_global.css?v=q0s1SprRKA7P&amp;l=english"
    rel="stylesheet" type="text/css">
  <link href="https://steamstore-a.akamaihd.net/public/shared/css/buttons.css?v=6uRURryOh96m&amp;l=english"
    rel="stylesheet" type="text/css">
  <link href="https://steamstore-a.akamaihd.net/public/css/v6/store.css?v=ZI_5VEPYpykL&amp;l=english" rel="stylesheet"
    type="text/css">
  <link href="https://steamstore-a.akamaihd.net/public/css/v6/home.css?v=Mr_QfRqGty0B&amp;l=english" rel="stylesheet"
    type="text/css">
  <link href="{% static 'css/autumn2019_sale.css' %}" rel="stylesheet">
  <link href="https://steamstore-a.akamaihd.net/public/shared/css/shared_responsive.css?v=GXt0zg7hRLhk&amp;l=english"
    rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link
    href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
    rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

  <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/bootstrap-datetimepicker.min.css' %}">
  <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/bootstrap-combined.min.css' %}">


  <link rel="stylesheet" type="text/css" href="https://cdn.rawgit.com/innks/NanumSquareRound/master/nanumsquareround.min.css">


  <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
    crossorigin="anonymous">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
  </script>

  <style>
   #video{
     
     min-width: 100%;
     min-height: 100%;
     width: 100%;
     height: 100%;
     z-index: -1;
     overflow: hidden;
   }

   
   html{
     font-family: NanumSquareRound;
   }
   
  {% block headstyle %}
  {% endblock %}
  </style>
</head>

<body>
<div id="video">
  {% comment %} <div style= "position: fixed; z-index: -99; width: 100%; height: 100%"> {% endcomment %}
    {% comment %} <iframe width="100%" height="100%" src="https://www.youtube.com/embed/wjAW0Kw4fU4?autoplay=1&autohide=1&loop=1&controls=0&modestbranding=1&disablekb=1&fs=0&rel=0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe> {% endcomment %}
        {% comment %} <iframe width="100%" height="100%" src="https://www.youtube.com/embed/wjAW0Kw4fU4?rel=0;autoplay=1;amp;loop=1" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe> {% endcomment %}
    <video style="position:absolute;" src="{% static 'video/hotplay_login.mp4' %}" autoplay="true" loop="loop" muted="muted" volumn="0"></video>

  {% comment %} </div> {% endcomment %}
  
   <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                  </div>
                  <form method="post">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <button class="btn btn-primary" style="width:100%;">LOGIN</button>
                  </form>
                  <div class="text-center">
                    <a style="color:#FFFFFF;" href="{% url 'accounts:signup' %}"><button class="btn btn-primary" style="width:100%;">SIGN UP</button></a>
                  </div>
                  <hr>
                  
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>
</div>
  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

</body>

</html>

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}
<h1>Signup!!</h1>

{% block content %}
<form method="post">
    {% csrf_token %}
     {% bootstrap_form form %} 
    <button class="btn btn-primary">signUp</button>
</form>
{% endblock  %}

accounts/templates/accounts/signup2.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>HOT Play</title>
  <!--Steam StyleSheet  -->
  <link href="https://use.typekit.net/bmd7vlq.css" rel="stylesheet" type="text/css">
  <link href="https://steamstore-a.akamaihd.net/public/shared/css/motiva_sans.css?v=FAK4O46_mOLB&amp;l=english"
    rel="stylesheet" type="text/css">
  <link href="https://steamstore-a.akamaihd.net/public/shared/css/shared_global.css?v=q0s1SprRKA7P&amp;l=english"
    rel="stylesheet" type="text/css">
  <link href="https://steamstore-a.akamaihd.net/public/shared/css/buttons.css?v=6uRURryOh96m&amp;l=english"
    rel="stylesheet" type="text/css">
  <link href="https://steamstore-a.akamaihd.net/public/css/v6/store.css?v=ZI_5VEPYpykL&amp;l=english" rel="stylesheet"
    type="text/css">
  <link href="https://steamstore-a.akamaihd.net/public/css/v6/home.css?v=Mr_QfRqGty0B&amp;l=english" rel="stylesheet"
    type="text/css">
  <link href="{% static 'css/autumn2019_sale.css' %}" rel="stylesheet">
  <link href="https://steamstore-a.akamaihd.net/public/shared/css/shared_responsive.css?v=GXt0zg7hRLhk&amp;l=english"
    rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link
    href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
    rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

  <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/bootstrap-datetimepicker.min.css' %}">
  <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/bootstrap-combined.min.css' %}">

  <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
    crossorigin="anonymous">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
  </script>

  {% block headstyle %}
  {% endblock %}
</head>

<body>

  <div class="container">

    <div class="card o-hidden border-0 shadow-lg my-5">
      <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
          <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
          <div class="col-lg-7">
            <div class="p-5">
              <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
              </div>
              <form method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                
                <button class="btn btn-primary" style="width:100%; font-size:20px;">SIGNUP</button>
              </form>
              <div class="text-center">
                <a class="small" href="{% url 'accounts:login' %}"><button class="btn btn-primary"
                    style="width:100%; font-size:20px;">Already have an Account? Login!</button></a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

</body>

</html>